                OUTPUT 2500AD
.ORG 2000H
DATA SEGMENT
NO1 DW 0050H
NO2 DW 0040H
LSB DW 0000H
MSB DB 00H
DATA ENDS
CODE SEGMENT
        ASSUME CS:CODE , DS:DATA
        MOV AX,DATA
        MOV DS,AX
        MOV AX,NO1
        MOV BX,NO2
        MUL BX
        MOV LSB,AX
        MOV MSB,DX
CODE ENDS
END
